import { StyleSheet } from 'react-native';
import { BRAND_BLUE } from './config/constants';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  safeLight: {
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 36,
  },
  containerLogin: {
    paddingHorizontal: 24,
    paddingTop: 48,
    gap: 18,
  },
  containerSignup: {
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  containerBuilder: {
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  loginShell: {
    flex: 1,
    gap: 18,
    backgroundColor: '#FFFFFF',
  },
  loginLogoWrap: {
    alignItems: 'center',
    marginBottom: 8,
  },
  loginLogo: {
    width: 300,
    height: 150,
  },
  loginLabel: {
    marginBottom: 6,
    fontWeight: '600',
  },
  loginInput: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 10,
    padding: 14,
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#111111',
    backgroundColor: 'transparent',
  },
  checkboxChecked: {
    backgroundColor: '#111111',
  },
  loginButton: {
    padding: 16,
    backgroundColor: '#111111',
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  loginButtonText: {
    color: BRAND_BLUE,
    fontWeight: '800',
  },
  signupFromLoginButton: {
    padding: 16,
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: BRAND_BLUE,
  },
  signupFromLoginText: {
    textAlign: 'center',
    fontWeight: '700',
    color: '#111111',
  },
  brand: {
    color: '#FACC15',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  title: {
    color: '#F8FAFC',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 20,
  },
  card: {
    backgroundColor: '#111827',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  signupContainer: {
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 30,
    gap: 14,
  },
  signupTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: '#111111',
  },
  signupRoleButton: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#CCFBF1',
    borderWidth: 1,
    borderColor: '#111111',
  },
  signupRoleButtonActive: {
    backgroundColor: '#111111',
    borderColor: '#111111',
  },
  signupRoleText: {
    fontWeight: '800',
    color: '#111111',
  },
  signupRoleTextActive: {
    color: BRAND_BLUE,
  },
  signupSubmitButton: {
    padding: 16,
    backgroundColor: '#111111',
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  signupSubmitText: {
    color: BRAND_BLUE,
    fontWeight: '800',
  },
  backToLoginText: {
    textAlign: 'center',
    fontWeight: '700',
    color: '#111111',
  },
  input: {
    backgroundColor: '#1F2937',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: '#E5E7EB',
    marginBottom: 12,
  },
  fieldWrap: {
    gap: 6,
  },
  fieldLabel: {
    fontWeight: '700',
    color: '#111111',
  },
  fieldInput: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 10,
    padding: 14,
    color: '#111111',
  },
  fieldInputMultiline: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  sectionLabel: {
    color: '#CBD5E1',
    fontSize: 14,
    marginBottom: 8,
  },
  roleRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
  },
  roleButton: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#334155',
    paddingVertical: 10,
    alignItems: 'center',
  },
  roleButtonActive: {
    backgroundColor: BRAND_BLUE,
    borderColor: BRAND_BLUE,
  },
  roleText: {
    color: '#CBD5E1',
    fontWeight: '600',
  },
  roleTextActive: {
    color: '#111827',
  },
  builderScroll: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  builderContent: {
    padding: 20,
    paddingTop: 20,
    paddingBottom: 24,
    gap: 20,
  },
  builderHeader: {
    gap: 6,
  },
  builderWelcome: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111111',
  },
  builderCompany: {
    fontSize: 28,
    fontWeight: '900',
    color: '#111111',
  },
  builderStatRow: {
    flexDirection: 'row',
    gap: 12,
  },
  builderActionsWrap: {
    gap: 12,
  },
  builderActionsTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#111111',
  },
  builderStatCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#111111',
  },
  builderStatValue: {
    fontSize: 24,
    fontWeight: '900',
    color: '#111111',
  },
  builderStatTitle: {
    marginTop: 6,
    opacity: 0.7,
    fontWeight: '700',
    color: '#111111',
  },
  builderActionButton: {
    padding: 16,
    borderRadius: 16,
  },
  builderActionButtonDark: {
    backgroundColor: '#111111',
  },
  builderActionButtonBrand: {
    backgroundColor: BRAND_BLUE,
  },
  builderActionLabel: {
    fontWeight: '900',
    fontSize: 16,
  },
  builderActionLabelDark: {
    color: '#333333',
  },
  builderActionLabelBrand: {
    color: BRAND_BLUE,
  },
  builderActionSubtitle: {
    marginTop: 4,
    fontWeight: '600',
  },
  builderActionSubtitleDark: {
    color: '#444444',
  },
  builderActionSubtitleBrand: {
    color: BRAND_BLUE,
  },
  builderTabPane: {
    marginTop: 60,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 16,
    padding: 20,
    backgroundColor: '#FFFFFF',
  },
  builderPaneTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#111111',
  },
  builderPaneBody: {
    marginTop: 8,
    color: '#333333',
    fontSize: 15,
  },
  jobsPage: {
    gap: 14,
  },
  builderSectionPage: {
    gap: 14,
  },
  builderSectionCard: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 16,
    padding: 20,
    backgroundColor: '#FFFFFF',
  },
  messagesLayout: {
    gap: 12,
  },
  messagesListCard: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 14,
    padding: 12,
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  messageTabs: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 12,
    padding: 4,
    gap: 4,
    backgroundColor: '#F3F4F6',
  },
  messageTabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingVertical: 9,
  },
  messageTabButtonActive: {
    backgroundColor: '#111111',
  },
  messageTabText: {
    color: '#111111',
    fontWeight: '700',
    fontSize: 13,
  },
  messageTabTextActive: {
    color: BRAND_BLUE,
  },
  messageThreadRow: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    gap: 2,
  },
  messageThreadTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  messageThreadRowActive: {
    backgroundColor: '#CCFBF1',
  },
  messageThreadName: {
    color: '#111111',
    fontWeight: '800',
    fontSize: 14,
  },
  messageThreadSubtitle: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '600',
  },
  messageUnreadBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    paddingHorizontal: 6,
    backgroundColor: '#111111',
    alignItems: 'center',
    justifyContent: 'center',
  },
  messageUnreadText: {
    color: BRAND_BLUE,
    fontWeight: '800',
    fontSize: 11,
  },
  messagesDetailCard: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 14,
    padding: 12,
    gap: 10,
    backgroundColor: '#FFFFFF',
  },
  messagesDetailTitle: {
    color: '#111111',
    fontWeight: '900',
    fontSize: 16,
  },
  messagesDetailHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  messageBackBtn: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: '#FFFFFF',
  },
  messageBackBtnText: {
    color: '#111111',
    fontWeight: '800',
    fontSize: 12,
  },
  messageCloseBtn: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: '#111111',
  },
  messageCloseBtnText: {
    color: BRAND_BLUE,
    fontWeight: '800',
    fontSize: 12,
  },
  messagesListWrap: {
    gap: 8,
  },
  messageBubble: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    maxWidth: '92%',
  },
  messageBubbleMine: {
    backgroundColor: BRAND_BLUE,
    alignSelf: 'flex-end',
  },
  messageBubbleOther: {
    backgroundColor: '#E5E7EB',
    alignSelf: 'flex-start',
  },
  messageBubbleText: {
    color: '#111111',
    fontWeight: '600',
    lineHeight: 18,
  },
  messageComposerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  messageComposerInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    color: '#111111',
  },
  messageSendBtn: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#111111',
  },
  messageSendText: {
    color: BRAND_BLUE,
    fontWeight: '800',
  },
  messageStatusText: {
    color: '#B91C1C',
    fontWeight: '700',
  },
  messageTypingText: {
    color: '#4B5563',
    fontWeight: '700',
    fontSize: 12,
  },
  tradieStartCard: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 14,
    padding: 12,
    backgroundColor: '#FFFFFF',
    gap: 8,
  },
  messageSectionTitle: {
    color: '#111111',
    fontWeight: '900',
    fontSize: 16,
  },
  tradieStartRow: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  messageStartAction: {
    color: '#111111',
    fontWeight: '800',
  },
  profileFields: {
    gap: 12,
  },
  profilePageContent: {
    gap: 2,
  },
  profileSaveBtn: {
    marginTop: 14,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#111111',
    alignItems: 'center',
  },
  profileSaveText: {
    color: BRAND_BLUE,
    fontWeight: '900',
  },
  jobsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  jobsHeaderTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#111111',
  },
  postJobButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: BRAND_BLUE,
    borderWidth: 1,
    borderColor: '#111111',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
  },
  postJobButtonText: {
    color: '#111111',
    fontWeight: '800',
  },
  jobsStatusTabs: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 12,
    padding: 4,
    gap: 4,
  },
  jobsStatusTabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
  },
  jobsStatusTabButtonActive: {
    backgroundColor: '#111111',
  },
  jobsStatusTabText: {
    color: '#111111',
    fontWeight: '700',
    fontSize: 13,
  },
  jobsStatusTabTextActive: {
    color: BRAND_BLUE,
  },
  jobsListWrap: {
    gap: 10,
  },
  jobsEmptyState: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 14,
    padding: 14,
    color: '#444444',
  },
  jobCard: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#FFFFFF',
  },
  jobCardActive: {
    backgroundColor: '#CCFBF1',
  },
  jobCardTitle: {
    color: '#111111',
    fontSize: 16,
    fontWeight: '800',
  },
  jobCardMeta: {
    marginTop: 4,
    color: '#444444',
    fontWeight: '600',
  },
  jobDetailsCard: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 16,
    padding: 16,
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  jobDetailsPage: {
    gap: 12,
  },
  jobBackButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#FFFFFF',
  },
  jobBackButtonText: {
    color: '#111111',
    fontWeight: '800',
    fontSize: 13,
  },
  jobDetailsTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#111111',
  },
  jobDetailsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  jobDetailsCloseBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#111111',
  },
  jobDetailsCloseText: {
    color: '#111111',
    fontWeight: '700',
    fontSize: 12,
  },
  jobDetailsMainTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111111',
  },
  jobDetailsSubheading: {
    marginTop: 6,
    color: '#111111',
    fontWeight: '800',
  },
  jobDetailsText: {
    color: '#333333',
    lineHeight: 20,
  },
  jobFieldLabel: {
    color: '#111111',
    fontWeight: '800',
  },
  jobInterestedItem: {
    color: '#333333',
    fontWeight: '600',
  },
  enquiryRow: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  enquiryTextWrap: {
    flex: 1,
    gap: 2,
  },
  enquiryName: {
    color: '#111111',
    fontWeight: '800',
    fontSize: 14,
  },
  enquiryOccupation: {
    color: '#4B5563',
    fontWeight: '600',
    fontSize: 12,
  },
  enquiryMessageBtn: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#111111',
  },
  enquiryMessageText: {
    color: BRAND_BLUE,
    fontWeight: '800',
    fontSize: 12,
  },
  builderLogoutBtn: {
    marginTop: 16,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#111111',
    alignItems: 'center',
  },
  builderLogoutText: {
    color: BRAND_BLUE,
    fontWeight: '900',
  },
  bottomTabs: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  bottomTabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingVertical: 2,
    borderRadius: 10,
  },
  bottomTabIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomTabText: {
    fontWeight: '700',
    fontSize: 12,
  },
  primaryButton: {
    backgroundColor: '#22C55E',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 2,
  },
  primaryText: {
    color: '#052E16',
    fontWeight: '700',
    fontSize: 16,
  },
  linkButton: {
    marginTop: 12,
    alignItems: 'center',
  },
  linkText: {
    color: BRAND_BLUE,
    fontSize: 14,
  },
  homeTitle: {
    color: '#F8FAFC',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 10,
  },
  homeBody: {
    color: '#CBD5E1',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 16,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
    padding: 14,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#111111',
    padding: 16,
    gap: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#111111',
  },
  modalSubtitle: {
    color: '#444444',
    lineHeight: 20,
    marginBottom: 2,
  },
  modalLabel: {
    color: '#111111',
    fontWeight: '700',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: '#111111',
  },
  modalDropdownText: {
    color: '#111111',
    fontWeight: '600',
  },
  tradeDropdownMenu: {
    borderWidth: 1,
    borderColor: '#111111',
    borderRadius: 10,
    overflow: 'hidden',
  },
  tradeDropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  tradeDropdownItemSelected: {
    backgroundColor: '#CCFBF1',
  },
  tradeDropdownItemText: {
    color: '#111111',
    fontWeight: '600',
  },
  tradeDropdownItemTextSelected: {
    fontWeight: '800',
  },
  modalInputMultiline: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 8,
  },
  modalButtonSecondary: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#111111',
    backgroundColor: '#FFFFFF',
  },
  modalButtonSecondaryText: {
    color: '#111111',
    fontWeight: '700',
  },
  modalButtonPrimary: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 10,
    backgroundColor: '#111111',
  },
  modalButtonPrimaryText: {
    color: BRAND_BLUE,
    fontWeight: '800',
  },
});
